---
- hosts: localhost
  gather_facts: false

  vars:
    # Facts from the upstream rulebook / job template
    node:       "{{ fact.node }}"
    cluster:    "{{ fact.cluster }}"
    controller: "{{ fact.controller }}"

  tasks:
    - name: Check node for Kubernetes pods
      when: cluster == 'k8s'
      shell: >
        kubectl get pods --field-selector=spec.nodeName={{ node }} --no-headers | wc -l
      delegate_to: "{{ controller }}"
      register: q

    - name: Check node for Slurm jobs
      when: cluster == 'slurm'
      shell: >
        squeue -h -w {{ node }} | wc -l
      delegate_to: "{{ controller }}"
      register: q

    - debug:
        msg: "Node {{ node }} idle = {{ q.stdout | int == 0 }}"

    # Mark the play 'changed' only when the node is idle
    - set_fact:
        _dummy: true
      changed_when: "{{ q.stdout | int == 0 }}"
