---
- hosts: localhost
  gather_facts: false

  vars:
    # Facts from the upstream rulebook / job template
    node: "{{ fact.target_node }}"

  tasks:
    - name: Check node for Slurm jobs
      shell: >
        squeue -h -w {{ node }} | wc -l
      delegate_to: fs-controller-001
      register: q

    - debug:
        msg: "Node {{ node }} idle = {{ q.stdout | int == 0 }}"

    # Mark the play 'changed' only when the node is idle
    - set_fact:
        _dummy: true
      changed_when: "{{ q.stdout | int == 0 }}"
