---
- hosts: localhost
  gather_facts: false
  vars:
    target_node: "{{ target_node }}"
    cluster_type: "{{ cluster_type }}"

  tasks:
    - name: Cordon Kubernetes node
      when: cluster_type == 'k8s'
      command: kubectl cordon {{ target_node }}

    - name: Drain Slurm node
      when: cluster_type == 'slurm'
      command: >
        scontrol update nodename={{ target_node }} state=drain reason="gpu error remediation"
