---
- hosts: localhost
  gather_facts: false
  become: true
  vars:
    target_node: "{{ target_node }}"

  tasks:

    - name: Drain Slurm node
      command: scontrol update nodename={{ target_node }} state=drain reason="gpu error remediation"
      delegate_to: fs-controller-001
